// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain,service} from '../models';

export function ExportCollection(arg1:string,arg2:string,arg3:string,arg4:service.ExportOptions):Promise<string>;

export function ImportCollection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<domain.Collection>;
