// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportCollection(arg1, arg2, arg3, arg4) {
  return window['go']['service']['CollectionService']['ExportCollection'](arg1, arg2, arg3, arg4);
}

export function ImportCollection(arg1, arg2, arg3, arg4) {
  return window['go']['service']['CollectionService']['ImportCollection'](arg1, arg2, arg3, arg4);
}
