// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DescribeService(arg1, arg2, arg3) {
  return window['go']['service']['GrpcService']['DescribeService'](arg1, arg2, arg3);
}

export function Invoke(arg1) {
  return window['go']['service']['GrpcService']['Invoke'](arg1);
}

export function ListMethods(arg1, arg2, arg3) {
  return window['go']['service']['GrpcService']['ListMethods'](arg1, arg2, arg3);
}

export function ListServices(arg1, arg2) {
  return window['go']['service']['GrpcService']['ListServices'](arg1, arg2);
}
