// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {transport} from '../models';

export function DescribeService(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function Invoke(arg1:transport.GrpcRequest):Promise<string>;

export function ListMethods(arg1:string,arg2:string,arg3:boolean):Promise<Array<string>>;

export function ListServices(arg1:string,arg2:boolean):Promise<Array<string>>;
