// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Consume(arg1) {
  return window['go']['service']['KafkaService']['Consume'](arg1);
}

export function Produce(arg1) {
  return window['go']['service']['KafkaService']['Produce'](arg1);
}
