// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {transport} from '../models';

export function Consume(arg1:transport.KafkaConsumeRequest):Promise<string>;

export function Produce(arg1:transport.KafkaProduceRequest):Promise<string>;
