// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreateCollection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CreateFolder(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function CreateOrganization(arg1:string,arg2:string):Promise<void>;

export function CreateProject(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:domain.Request):Promise<void>;

export function DeleteCollection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteFolder(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteOrganization(arg1:string):Promise<void>;

export function DeleteProject(arg1:string,arg2:string):Promise<void>;

export function DeleteRequest(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function LoadOrganizations():Promise<Array<domain.Organisation>>;

export function RenameCollection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RenameFolder(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function RenameOrganization(arg1:string,arg2:string):Promise<void>;

export function RenameProject(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdateRequest(arg1:string,arg2:string,arg3:string,arg4:domain.Request):Promise<void>;
