// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCollection(arg1, arg2, arg3, arg4) {
  return window['go']['service']['OrganizationService']['CreateCollection'](arg1, arg2, arg3, arg4);
}

export function CreateFolder(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['service']['OrganizationService']['CreateFolder'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateOrganization(arg1, arg2) {
  return window['go']['service']['OrganizationService']['CreateOrganization'](arg1, arg2);
}

export function CreateProject(arg1, arg2, arg3) {
  return window['go']['service']['OrganizationService']['CreateProject'](arg1, arg2, arg3);
}

export function CreateRequest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['service']['OrganizationService']['CreateRequest'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteCollection(arg1, arg2, arg3) {
  return window['go']['service']['OrganizationService']['DeleteCollection'](arg1, arg2, arg3);
}

export function DeleteFolder(arg1, arg2, arg3, arg4) {
  return window['go']['service']['OrganizationService']['DeleteFolder'](arg1, arg2, arg3, arg4);
}

export function DeleteOrganization(arg1) {
  return window['go']['service']['OrganizationService']['DeleteOrganization'](arg1);
}

export function DeleteProject(arg1, arg2) {
  return window['go']['service']['OrganizationService']['DeleteProject'](arg1, arg2);
}

export function DeleteRequest(arg1, arg2, arg3, arg4) {
  return window['go']['service']['OrganizationService']['DeleteRequest'](arg1, arg2, arg3, arg4);
}

export function LoadOrganizations() {
  return window['go']['service']['OrganizationService']['LoadOrganizations']();
}

export function RenameCollection(arg1, arg2, arg3, arg4) {
  return window['go']['service']['OrganizationService']['RenameCollection'](arg1, arg2, arg3, arg4);
}

export function RenameFolder(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['service']['OrganizationService']['RenameFolder'](arg1, arg2, arg3, arg4, arg5);
}

export function RenameOrganization(arg1, arg2) {
  return window['go']['service']['OrganizationService']['RenameOrganization'](arg1, arg2);
}

export function RenameProject(arg1, arg2, arg3) {
  return window['go']['service']['OrganizationService']['RenameProject'](arg1, arg2, arg3);
}

export function RenameRequest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['service']['OrganizationService']['RenameRequest'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateRequest(arg1, arg2, arg3, arg4) {
  return window['go']['service']['OrganizationService']['UpdateRequest'](arg1, arg2, arg3, arg4);
}
