// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function ClearCookies():Promise<void>;

export function ExecuteRequest(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>):Promise<domain.Response>;
