// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {transport} from '../models';

export function Receive(arg1:transport.SqsReceiveRequest):Promise<string>;

export function Send(arg1:transport.SqsSendRequest):Promise<string>;
