// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {transport} from '../models';

export function Connect(arg1:transport.WsConnectRequest):Promise<string>;
