// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {transport} from '../models';

export function Close(arg1:string):Promise<void>;

export function Connect(arg1:transport.WsConnectRequest):Promise<string>;

export function Open(arg1:transport.WsOpenRequest):Promise<string>;

export function Send(arg1:string,arg2:string):Promise<void>;
