// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close(arg1) {
  return window['go']['service']['WsService']['Close'](arg1);
}

export function Connect(arg1) {
  return window['go']['service']['WsService']['Connect'](arg1);
}

export function Open(arg1) {
  return window['go']['service']['WsService']['Open'](arg1);
}

export function Send(arg1, arg2) {
  return window['go']['service']['WsService']['Send'](arg1, arg2);
}
