// Code generated by MockGen. DO NOT EDIT.
// Source: simora/backend/service (interfaces: OrganizationRepository)
//
// Generated by this command:
//
//	mockgen -destination=../test/mock/repository/organization.go -package=mock . OrganizationRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	domain "simora/backend/domain"
)

// MockOrganizationRepository is a mock of OrganizationRepository interface.
type MockOrganizationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationRepositoryMockRecorder
	isgomock struct{}
}

// MockOrganizationRepositoryMockRecorder is the mock recorder for MockOrganizationRepository.
type MockOrganizationRepositoryMockRecorder struct {
	mock *MockOrganizationRepository
}

// NewMockOrganizationRepository creates a new mock instance.
func NewMockOrganizationRepository(ctrl *gomock.Controller) *MockOrganizationRepository {
	mock := &MockOrganizationRepository{ctrl: ctrl}
	mock.recorder = &MockOrganizationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationRepository) EXPECT() *MockOrganizationRepositoryMockRecorder {
	return m.recorder
}

// LoadOrganizations mocks base method.
func (m *MockOrganizationRepository) LoadOrganizations() ([]domain.Organisation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadOrganizations")
	ret0, _ := ret[0].([]domain.Organisation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadOrganizations indicates an expected call of LoadOrganizations.
func (mr *MockOrganizationRepositoryMockRecorder) LoadOrganizations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadOrganizations", reflect.TypeOf((*MockOrganizationRepository)(nil).LoadOrganizations))
}

// SaveOrganizations mocks base method.
func (m *MockOrganizationRepository) SaveOrganizations(organisations []domain.Organisation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOrganizations", organisations)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveOrganizations indicates an expected call of SaveOrganizations.
func (mr *MockOrganizationRepositoryMockRecorder) SaveOrganizations(organisations any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOrganizations", reflect.TypeOf((*MockOrganizationRepository)(nil).SaveOrganizations), organisations)
}
