// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ClearCrashReports():Promise<void>;

export function GetConfigDir():Promise<string>;

export function GetCrashReport():Promise<string>;

export function GetVersion():Promise<string>;

export function OpenConfigDir():Promise<void>;

export function ReportCrash(arg1:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;
