// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearCrashReports() {
  return window['go']['main']['App']['ClearCrashReports']();
}

export function GetCrashReport() {
  return window['go']['main']['App']['GetCrashReport']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ReportCrash(arg1) {
  return window['go']['main']['App']['ReportCrash'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}
