// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function GetVersion():Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;
